# Generated by Django 5.1 on 2024-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('course_no', models.IntegerField(primary_key=True, serialize=False)),
                ('course_timings', models.CharField(max_length=20)),
                ('course_duration', models.CharField(max_length=20)),
                ('course_startdate', models.DateField()),
                ('course_fee', models.IntegerField()),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
    ]
