# Generated by Django 5.1 on 2024-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='trainer_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
