# Generated by Django 5.1 on 2024-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0002_coursedata_trainer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
